column_mappings:
  # Map original CSV column names to snake_case
  group_id: GroupID
  plan_id: PlanID
  first_name: FirstName
  last_name: LastName
  gender: Gender
  date_of_birth: DOB
  subscriber_ssn: SubscriberSSN
  relationship_code: RelationshipCode
  enrollment_start_date: EnrollmentStart
  enrollment_end_date: EnrollmentEnd
  benefit_type: BenefitType
  benefit_minimum: BenefitMinimum
  benefit_max: BenefitMax